#pragma once

// PINS

#define DISPLAY_CLK_PIN 32
#define DISPLAY_DIO_PIN 25

#define DHT_PIN 33

#define ROTARY_ENCODER_A_PIN 34
#define ROTARY_ENCODER_B_PIN 35
#define ROTARY_ENCODER_BUTTON_PIN 26

#define HEATER_PIN 5

// TASK PRIORITIES

#define TASK_PRIORITY 2
